<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Recipe;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository implements RecipeRepositoryInterface
{

    const LIMIT = 3;

    /**
     * CharacterRepository constructor.
     * @param EntityManager $entityManager
     */
    public function __construct(EntityManager $entityManager)
    {
        $this->_em = $entityManager;
    }

    /**
     * @param Recipe $recipe
     * @return Recipe
     */
    public function save(Recipe $recipe): Recipe
    {
        $this->getEntityManager()->persist($recipe);
        $this->getEntityManager()->flush();

        return $recipe;
    }

    /**
     * @param $id
     * @return Recipe
     */
    public function findRecipe($id): Recipe
    {
        return $this->getEntityManager()->find('AppBundle:Recipe',$id);
    }

    /**
     * @param $page
     * @return array
     */
    public function findAllRecipes($page,$cuisine): array
    {
        $offSet = ($page - 1) * self::LIMIT;

        $query = $this->getEntityManager()->createQuery(
            'SELECT p FROM AppBundle:Recipe p  where p.recipeCuisine = :cuisine ORDER BY p.id ASC'
        );
        $query->setParameter('cuisine', $cuisine);

        $query->setMaxResults(self::LIMIT);
        $query->setFirstResult($offSet);
        return $query->getResult();
    }
}
