services:

    recipe_service:
        class: AppBundle\Service\RecipeService
        arguments:
            - "@recipe_repo"

    recipe_repo:
        class: AppBundle\Repository\RecipeRepository
        arguments:
            - "@doctrine.orm.entity_manager"

    recipe_porter:
            class: AppBundle\Service\RecipePorter